---
- name: Install nginx
  yum: name=nginx state=present

- name: Copy nginx configuration for wordpress
  template: src=templates/default.conf dest=/etc/nginx/conf.d/default.conf
  

- name: http service state
  service: name=nginx state=started enabled=yes
